version: "3.5"
x-environment:
  &QUICKSTART_ENVIRONMENT # These are read from .env file. The values in the .env file maybe overriden by shell envvars
  PLAID_CLIENT_ID: ${PLAID_CLIENT_ID}
  PLAID_SECRET: ${PLAID_SECRET}
  PLAID_PRODUCTS: ${PLAID_PRODUCTS}
  PLAID_COUNTRY_CODES: ${PLAID_COUNTRY_CODES}
  PLAID_REDIRECT_URI: ${PLAID_REDIRECT_URI}
  PLAID_ENV: ${PLAID_ENV}
  REACT_APP_API_HOST: ${REACT_APP_API_HOST}
services:
  fluentbit:
    container_name: fluentbit
    image: fluent/fluent-bit:1.9.0
    build:
      context: ./fluent-bit
    networks:
      - quickstart
    ports:
      - "24224:24224"
      - "24224:24224/udp"
  server:
    container_name: server
    networks:
      - quickstart
    depends_on:
      - frontend
      - fluentbit
    build:
      context: .
      dockerfile: ./python/Dockerfile
    ports: ["8000:8000"]
    environment:
      <<: *QUICKSTART_ENVIRONMENT
    logging:
      driver: "fluentd"
      options:
        tag: server
  frontend:
    container_name: frontend
    image: sanlimag/cs-fintech-frontend:1.0
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
    environment:
      <<: *QUICKSTART_ENVIRONMENT
    networks:
      - quickstart
    ports: ["3000:3000"]
    depends_on:
      - fluentbit
    logging:
      driver: "fluentd"
      options:
        tag: frontend
  nginx:
    container_name: nginx
    build:
      context: ./nginx
    ports:
      - "80:80"
    networks:
      - quickstart
    depends_on:
      - fluentbit
      - server
      - frontend
    logging:
      driver: "fluentd"
      options:
        tag: nginx
networks:
  quickstart:
    name: quickstart